name: Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  create-cisco-configs:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar contenido del repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: 📦 Crear ambiente virtual e instalar dependencias
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Ejecutar script principal
        run: |
          source venv/bin/activate
          python3 main.py

      - name: 🧪 Ejecutar pruebas con Pytest
        run: |
          source venv/bin/activate
          python3 -m pytest -v 
